// Generated by CoffeeScript 1.8.0
(function() {
  var Contacts, americano, createRequest, mapSharedDoc;

  americano = require("americano");

  module.exports = Contacts = americano.getModel('Contact', {
    "id": String,
    "fn": String,
    "n": String,
    "datapoints": function(x) {
      return x;
    },
    "note": String,
    "shared": Boolean
  });

  mapSharedDoc = function(doc) {
    if (doc.shared) {
      emit(doc._id, doc);
    }
  };

  (createRequest = function() {
    console.log('request creation');
    return Contacts.defineRequest("shared", mapSharedDoc, function(err) {
      if (err) {
        return console.log(err);
      }
    });
  })();

  module.exports.deleteAll = function(callback) {
    return Contacts.requestDestroy("all", function(err) {
      return callback(err);
    });
  };

  module.exports.createContacts = function(nDocs, baseName, callback) {
    var cpt, i, ids, _i, _results;
    ids = [];
    cpt = 0;
    _results = [];
    for (i = _i = 0; 0 <= nDocs ? _i <= nDocs : _i >= nDocs; i = 0 <= nDocs ? ++_i : --_i) {
      _results.push(createSingleContact(baseName, function(err, result) {
        if (err) {
          callback(err);
        }
        ids.push(result.id);
        if (cpt === nDocs) {
          return callback(null, ids);
        }
      }));
    }
    return _results;
  };

  module.exports.createSingleContact = function(baseName, callback) {
    return Contacts.create({
      fn: baseName
    }, function(err, result) {
      return callback(err, result.id);
    });
  };

  module.exports.getSharedContacts = function(callback) {
    return Contacts.request("shared", function(err, results) {
      var getIds, res;
      if (results) {
        getIds = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = results.length; _i < _len; _i++) {
            res = results[_i];
            _results.push(res.id);
          }
          return _results;
        })();
        return callback(err, getIds);
      } else {
        return callback(err);
      }
    });
  };

}).call(this);
