// Generated by CoffeeScript 1.10.0
(function() {
  var Contacts, cozydb, createRequest, createSingleContact, mapSharedDoc;

  cozydb = require("cozydb");

  module.exports = Contacts = cozydb.getModel('Contact', {
    "id": String,
    "fn": String,
    "n": String,
    "datapoints": function(x) {
      return x;
    },
    "note": String,
    "shared": Boolean
  });

  mapSharedDoc = function(doc) {
    if (doc.shared) {
      emit(doc._id, doc);
    }
  };

  (createRequest = function() {
    console.log('request creation');
    return Contacts.defineRequest("shared", mapSharedDoc, function(err) {
      if (err) {
        return console.log(err);
      }
    });
  })();

  module.exports.deleteAll = function(callback) {
    return Contacts.requestDestroy("all", function(err) {
      return callback(err);
    });
  };

  module.exports.createContacts = function(nDocs, baseName, callback) {
    var cpt, i, ids, j, ref, results1;
    ids = [];
    cpt = 0;
    results1 = [];
    for (i = j = 0, ref = nDocs; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results1.push(createSingleContact(baseName, function(err, result) {
        if (err) {
          return callback(err);
        } else {
          ids.push(result.id);
          cpt++;
          if (cpt === nDocs) {
            return callback(null, ids);
          }
        }
      }));
    }
    return results1;
  };

  createSingleContact = module.exports.createSingleContact = function(baseName, callback) {
    return Contacts.create({
      fn: baseName
    }, function(err, result) {
      return callback(err, result.id);
    });
  };

  module.exports.getSharedContacts = function(callback) {
    return Contacts.request("shared", function(err, results) {
      var getIds, res;
      if (results) {
        getIds = (function() {
          var j, len, results1;
          results1 = [];
          for (j = 0, len = results.length; j < len; j++) {
            res = results[j];
            results1.push(res.id);
          }
          return results1;
        })();
        return callback(err, getIds);
      } else {
        return callback(err);
      }
    });
  };

}).call(this);
