// Generated by CoffeeScript 1.8.0
(function() {
  var contacts, request;

  contacts = require('../models/contacts');

  request = require('request-json');

  module.exports.list = function(req, res, next) {
    return contacts.request('all', function(error, contacts) {
      if (error) {
        return next(error);
      }
      return plug.filterContactsPlug(contacts, function(err, filteredContacts) {
        if (err) {
          return next(error);
        }
        return res.send(filteredContacts);
      });
    });
  };

  module.exports.get = function(req, res, next) {
    return contacts.find(req.params.id, function(error, contact) {
      if (error) {
        return next(error);
      }
      return res.send(contact);
    });
  };

  module.exports.change = function(req, res, next) {
    console.log('log1');
    return contacts.find(req.params.id, function(error, contact) {
      console.log('log2', req.body, error);
      if (error) {
        return next(error);
      }
      return contact.updateAttributes(req.body, function(error, contact) {
        console.log('log3', contact);
        if (error) {
          return next(error);
        }
        return res.send(contact);
      });
    });
  };


  /*
  var getIdsContacts = function(callback) {
      // Getting request results
      Contact.request("all", function (err, contacts) {
          if(err){
              console.error(err);
              return;
          }
          else{
              var ids = [];
              for(var i=0;i<contacts.length;i++){
                  console.log("contact : " + contacts[i]);
                  if(contacts[i].shared)
                      ids.push(contacts[i].id);
              }
              callback(ids);
          }
      });
  };
   */


  /*  function(nDocs, baseName, callback) {
      var ids = [];
      var cpt = 0;
      for(var i=0; i<nDocs; i++) {
          createCozyContact(baseName, function(id) {
              ids.push(id);
              cpt++;
              console.log('id' + id + ' in array - cpt = ' + cpt + ' (ndocs = ' + nDocs);
              if(cpt == nDocs ){
                  console.log('done');
                  callback(ids);
              }
          });
      }
      };
      
  
  
  
  var createCozyContact = function(baseName, callback) {
      var datapoint = new Array();
      Contact.create({fn: baseName, datapoints: datapoint }, function(err, contact) {
          if(err)
              callback(err);
  
          else{
              log.raw('contact created : ' + contact.id);
              callback(contact.id);
          }
      });
      };
   */

}).call(this);
